server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/secure_event_booking
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000